version: '2'

services:
  web:
    build: .
    ports:
      - 80:80
    volumes:
      - ./ARte/:/app/
    env_file:
      - ./.envs/.django
      - ./.envs/.postgres
    depends_on:
      - postgres
    command: db -p collect run -p

  postgres:
    image: postgres
    env_file:
      - ./.envs/.postgres
    ports:
      - "5432:5432"
