name: Jandig's Django build

on:
  push:
    branches:
      - 'master'
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Build Jandig's Django image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        tags: jandigarte/django:latest
        outputs: type=docker,dest=/tmp/latestimage.tar

    - name: Upload artifact for next jobs
      uses: actions/upload-artifact@v2
      with:
        name: latestimage
        path: /tmp/latestimage.tar


  push_dev:
    runs-on: ubuntu-latest
    if: github.event.ref == 'refs/heads/develop'
    needs: [build]
    steps:

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: latestimage
        path: /tmp

    - name: Load Docker image
      run: docker load --input /tmp/latestimage.tar

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASS }}

    - name: Push To Registry
      run: | 
          docker tag jandigarte/django:latest jandigarte/django:dev
          docker push jandigarte/django:dev