name: CI pipeline

on: push

jobs:
  linter:
    name: run / linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from Github
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Installing flake8
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run flake8 linter
        run: |
          flake8 --max-line-length=200 src/

  build:
    name: run / build
    runs-on: ubuntu-latest
    needs: linter
    steps:
      - name: Check out code from Github
        uses: actions/checkout@v3
      - name: Build image
        run: |
          # docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
          docker build . -f docker/Dockerfile -t jandigarte/django:$GITHUB_SHA
          docker save -o docker_image_$GITHUB_SHA jandigarte/django:$GITHUB_SHA
      - name: Caching image
        uses: actions/cache@v3
        with:
          key: jandigarte
          path: docker_image_${{ github.sha }}

  migrations:
    name: test / migrations
    runs-on: ubuntu-latest
    needs: linter
    steps:
      - name: Check out code from Github
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
      - name: Test migrations
        run: |
          python src/ARte/manage.py makemigrations --check --dry-run
          python src/ARte/manage.py migrate
