name: Docker Image CI

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'github-actions'
    tags:
      - '*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - uses: actions/checkout@v2
    - name: Build Jandig's Django image
      run: docker build . -f docker/Dockerfile  -t jandigarte/django:${{ steps.extract_branch.outputs.branch }}
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PASS }}
    - name: Push To Registry
      run: docker push jandigarte/django:${{ steps.extract_branch.outputs.branch }}