name: Docker pipeline

on: pull_request

# TODO: Change environment and login envs
jobs:
  django:
    name: push / django 
    environment: testes
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - name: Check out code from Github
        uses: actions/checkout@v3
      - name: Build django image
        run: |
          docker build . -f docker/Dockerfile -t jandigarte/django:latest
      - name: Push django image
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASS }}
          docker push jandigarte/django:latest
